### ISSUE TITLE
Wire in Inclusion verification post addLeaf

### ISSUE THREAD

**Issue by lukehinds** [projectrekor/rekor-server#11]

**Comment by dlorenc** [comment]
Just for my own education, what is the purpose of this? Just to add a sanity check inside the server (personality) that trillian acted correctly, on top of the response/error code?

**Comment by lukehinds** [comment]
Yep, pretty much. when using `add` the server trillian will reply that it has queued the leaf, calling `GetInclusionProofByHash` will ensure its actually hashed into the tree.

The function is already there, we just need some sort of poll / wait after add to verify its in. 

Having thought about it though, I think clients should look after this and make the call themselves. So they would call `add` and then `getproof` as a follow up, this means less connections tied up for less time awaiting an inclusion proof.
