### ISSUE TITLE
Validate incoming entries

### ISSUE THREAD

**Issue by dlorenc** [projectrekor/rekor-server#22]
They should be:

- Valid in_toto Link files
- With a valid signature

**Comment by dlorenc** [comment]
In order to check the signature is valid, we'll first have to figure out a way to find the public key. We could require the user to attach that to the request as well, or just skip signature validation.

**Comment by lukehinds** [comment]
> Valid in_toto Link files

We should think about how we can make this pluggable whenever we can, along the lines of the whole fomatgility that we chatted about.

> In order to check the signature is valid, we'll first have to figure out a way to find the public key. We could require the user to attach that to the request as well, or just skip signature validation.

I reckon we can attach to the request for now just as a makeshift approach until we work out what key server / PKI implementation we can use.

**Comment by lukehinds** [comment]
Some more on this:

Implement some basic checks, all configurable in rekor-config.yaml

* `max_size` # stop people bombing the server with large files (this may already be natively handled in `FormFile`?)

* `allowed_file_formats` # this way we can limit to just `text/plain`, perhaps use `http.DetectContentType`

* `format_type` # e.g. `in-toto` - this can be used for the specific validation. I am seeing this as almost a plugin type framework, so users can integrate their own provenance formats and logic (check for sig etc).

**Comment by lukehinds** [comment]
I think we can close this now @dlorenc ?
