### ISSUE TITLE
Wayward err return

### ISSUE THREAD

**Issue by lukehinds** [projectrekor/rekor-server#25]
We just need to look at err handling returns from grpc

We return an `err` to the `API` struct instance (is that the right golang idiom?) 

https://github.com/projectrekor/rekor-server/blob/97ec32e09dfa0acc117ae22909c6d13fe3e80921/app/api.go#L47-L50

But we don't have anywhere to capture that `err` in the API handlers, e.g.:

https://github.com/projectrekor/rekor-server/blob/97ec32e09dfa0acc117ae22909c6d13fe3e80921/app/api.go#L92-L99

Meanwhile we handle err's locally in `gprc.go` (which we should be returning if we are checking for it in the calling function)

https://github.com/projectrekor/rekor-server/blob/97ec32e09dfa0acc117ae22909c6d13fe3e80921/app/gprc_client.go#L16-L20

Not a high priority item by any means, as we capture the connection failure:

```
2020-09-17T12:10:10.528+0100    INFO    cmd/root.go:87  Using config file: /home/luke/go/src/github.com/lukehinds/rekor-server/rekor-server.yaml
2020/09/17 12:10:10 rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8091: connect: connection refused"
exit status 1
```

But logging this so we can look at it later so we can tell the rekor sever user which node being called failed (mapserver, logserver). We will likely want to refactor the grpc handler later (when we run in Secure mode or use more options), so we can always do it then.

**Comment by dlorenc** [comment]
Your last example (the fatal one) isn't an issue - the Fatal call will actually force a panic and an os.Exit. We may want to just return it and let something higher up fail though.

**Comment by lukehinds** [comment]
> Your last example (the fatal one) isn't an issue - the Fatal call will actually force a panic and an os.Exit. We may want to just return it and let something higher up fail though.

Agree!
