### ISSUE TITLE
Monitor based API 

### ISSUE THREAD

**Issue by lukehinds** [projectrekor/rekor-server#30]
Provide an API in rekor that a monitor can use to tail and build its own tree that can then be processed accordingly to the monitors functional needs (parse out a provenence file for whatever its monitoring).

Having taking a cursory look, I believe we need to make use of the `GetLeavesByRange` \ `GetLeavesByIndex` calls. A monitor can then pull down leafs from index value of `0` to the complete treesize. They can then monitor the treesize and an increment of >1 means new entries are available to pull down. 

A good example here:

https://github.com/benlaurie/trillian-examples/blob/39a83ab3df9b83997733e2c05c730accb7e336b9/registers/trillian_client/client.go#L46-L88

```golang
func (t *trillianClient) Scan(logID int64, s LogScanner) error {
	ctx := context.Background()


	rr := &trillian.GetLatestSignedLogRootRequest{LogId: logID}
	lr, err := t.tc.GetLatestSignedLogRoot(ctx, rr)
	if err != nil {
		log.Fatalf("Can't get log root: %v", err)
	}


	ts := lr.SignedLogRoot.TreeSize
	for n := int64(0); n < ts; {
		g := &trillian.GetLeavesByRangeRequest{LogId: logID, StartIndex: n, Count: chunk}
		r, err := t.tc.GetLeavesByRange(ctx, g)
		if err != nil {
			return fmt.Errorf("Can't get leaf %d: %v", n, err)
		}


		// Deal with server skew, if tree size has reduced.
		// Don't allow increases so this terminates eventually.
		rts := r.SignedLogRoot.TreeSize
		if rts < ts {
			ts = rts
		}


		if n < ts && len(r.Leaves) == 0 {
			return fmt.Errorf("No progress at leaf %d", n)
		}


		for m := 0; m < len(r.Leaves) && n < ts; n++ {
			if r.Leaves[m] == nil {
				return fmt.Errorf("Can't get leaf %d (no error)", n)
			}
			if r.Leaves[m].LeafIndex != n {
				return fmt.Errorf("Got index %d expected %d", r.Leaves[n].LeafIndex, n)
			}
			err := s.Leaf(r.Leaves[m])
			if err != nil {
				return err
			}
			m++
		}
	}
	return nil
```
Need to think about the two use cases:

1. I am a monitor and I want everything
2. I am monitor, I have everything, I just want the latest index entry.

Method 1 is going to be quite resource intensive (unless I have missed something). If we have a massive tree and a monitor wants the whole lot, how are we going to manage that. We can add in some form of rate limiter to protect the service, but is there a cheaper way of catering to this use case.

**Comment by lukehinds** [comment]
feel free to comment @dlorenc , this is more a planning / design discussion.

**Comment by dlorenc** [comment]
I think we'll need a way to fetch pages of them. Something like 100 entries max at a time, paginated. Then rate-limiting, eventually.
