### ISSUE TITLE
Cannot make duplicate entries

### ISSUE THREAD

**Issue by lukehinds** [projectrekor/rekor-server#38]
Currently we reject duplicate entries with `{Data Already Exists}` where as we should allow mutiple entries (so that we can prevent an attacker placing a file into the tree before the rightful owner makes an entry). 

I think we can work around this by using `ExtraData` with timestamp to make every entry unique.

**Comment by lukehinds** [comment]
Tested Extra data but it has no bearing on the hash.

**Comment by dlorenc** [comment]
I think we need to get crisp on what the data we're storing is. Depending on the formats, we may not need to allow duplicate entries.

**Comment by lukehinds** [comment]
I should have updated this bug, as I am seeing this as more of a non issue. If an attacker were to do this, all they would do is make the entry on behalf of the rightful project owner (with all the correct contents).

**Comment by dlorenc** [comment]
Right. If we validate signatures it doesn't matter who uploads the contents.
